version: '3'
volumes:
  docker:
services:
  

  yobulk:
    image: yobulk/yobulk
    ports:
      - 5050:5050
    environment:
      MONGODB_URI: mongodb://database:27017/yobulk
      DATABASE_NAME: 'yobulk'
      OPENAI_SECRET_KEY: your openai key
      BACKEND_SERVER_HOST: 'http://localhost:5050'
 
